// <auto-generated />
using System;
using LakDerana_HotelChainManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LakDerana_HotelChainManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220111062010_IdenityTableUpdated_AddedHotelIDToEmpIDentityTable")]
    partial class IdenityTableUpdated_AddedHotelIDToEmpIDentityTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LakDerana_HotelChainManagement.Models.AttendanceMaintenanceModel", b =>
                {
                    b.Property<string>("AttendanceLogID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttendanceLogID");

                    b.ToTable("Tbl_AttendanceMaintenance");
                });

            modelBuilder.Entity("LakDerana_HotelChainManagement.Models.AttendanceSheetModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttendanceLogID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttendanceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tbl_AttendanceSheet");
                });

            modelBuilder.Entity("LakDerana_HotelChainManagement.Models.BarModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmpUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Expense")
                        .HasColumnType("money");

                    b.Property<string>("HotelID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IncomeExpenseUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Sales")
                        .HasColumnType("money");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tbl_BarIncomeExpense");
                });

            modelBuilder.Entity("LakDerana_HotelChainManagement.Models.CustomerModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CusAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusNIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusfName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuslName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tbl_Customer");
                });

            modelBuilder.Entity("LakDerana_HotelChainManagement.Models.EmpIdentityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmpEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpIDID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmpPassWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpIDID");

                    b.ToTable("tbl_EmpLogin");
                });

            modelBuilder.Entity("LakDerana_HotelChainManagement.Models.EmployeeModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tbl_Employee");
                });

            modelBuilder.Entity("LakDerana_HotelChainManagement.Models.HotelModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HotelLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelSpecialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomServiceManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tbl_Hotel");
                });

            modelBuilder.Entity("LakDerana_HotelChainManagement.Models.HotelRoomModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HotelID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RoomPricePerNight")
                        .HasColumnType("money");

                    b.Property<string>("RoomStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tbl_HotelRoom");
                });

            modelBuilder.Entity("LakDerana_HotelChainManagement.Models.PaymentModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AdvancePaymentAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("money");

                    b.Property<DateTime>("FinalPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HotelServiceCharge")
                        .HasColumnType("money");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("money");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReservationFee")
                        .HasColumnType("money");

                    b.Property<string>("ReservationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPayableAmount")
                        .HasColumnType("money");

                    b.HasKey("ID");

                    b.ToTable("Tbl_Payments");
                });

            modelBuilder.Entity("LakDerana_HotelChainManagement.Models.ReservationModel", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hotel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tbl_Reservation");
                });

            modelBuilder.Entity("LakDerana_HotelChainManagement.Models.ReservedRoomModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CurrentRoomCharge")
                        .HasColumnType("money");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPayableAmount")
                        .HasColumnType("money");

                    b.HasKey("ID");

                    b.ToTable("Tbl_ReservedRoom");
                });

            modelBuilder.Entity("LakDerana_HotelChainManagement.Models.EmpIdentityModel", b =>
                {
                    b.HasOne("LakDerana_HotelChainManagement.Models.EmployeeModel", "EmpID")
                        .WithMany()
                        .HasForeignKey("EmpIDID");
                });
#pragma warning restore 612, 618
        }
    }
}
